name: hello_world CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prJob:    
    name: Print info
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo github.event.action="${{ github.event.action }}"
          echo HOME=$HOME
          echo GITHUB_WORKFLOW=$GITHUB_WORKFLOW
          echo GITHUB_RUN_ID=$GITHUB_RUN_ID
          echo GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER
          echo GITHUB_ACTION=$GITHUB_ACTION
          echo GITHUB_ACTIONS=$GITHUB_ACTIONS
          echo GITHUB_ACTOR=$GITHUB_ACTOR
          echo GITHUB_REPOSITORY=$GITHUB_REPOSITORY
          echo GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME
          echo GITHUB_EVENT_PATH=$GITHUB_EVENT_PATH
          echo GITHUB_WORKSPACE=$GITHUB_WORKSPACE
          echo GITHUB_SHA=$GITHUB_SHA
          echo GITHUB_REF=$GITHUB_REF
          echo GITHUB_HEAD_REF=$GITHUB_HEAD_REF
          echo GITHUB_BASE_REF=$GITHUB_BASE_REF
    
